{{- if (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-scripts.fullname" . }}
  labels:
    {{- include "argocd-scripts.labels" . | nindent 4 }}
type: Opaque
data:
  argoURL: {{ default "" .Values.secrets.argoURL | b64enc | quote }}
  argoToken: {{ default "" .Values.secrets.argoToken | b64enc | quote }}
  jupiteroneAccountId: {{ default "" .Values.secrets.jupiteroneAccountId | b64enc | quote }}
  jupiteroneApiKey: {{ default "" .Values.secrets.jupiteroneApiKey | b64enc | quote }}
{{- end }}